name: Run Tests

on: [ push, pull_request ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ~4.4.2

      - name: Install ALSA
        run: |
          sudo apt update
          sudo apt install -y libasound2-dev

      - name: Install Dependencies
        run: sudo apt install -y libsndfile1-dev libsamplerate0-dev

      - name: Build RtAudio
        run: |
          git clone https://github.com/thestk/rtaudio
          cd rtaudio
          cmake -B build
          cd build
          sudo make install

      - name: Build
        run: |
          cmake -B build
          cmake --build build --config Release

      - name: Test
        run: ./build/organic_test
